version: '2'
services:    
  spark-cassandra-master:
    container_name: spark-cassandra-master
    command: cassandra -f
    image: dawidnowak/spark-cassandra:2.1
    environment:
      SPARK_MODE: master
      CASSANDRA_SEEDS: spark-cassandra-master
    mem_limit: 2g
      

    
  spark-cassandra-node:
    image: dawidnowak/spark-cassandra:2.1
    command: cassandra -f
    environment:
      CASSANDRA_SEEDS: spark-cassandra-master
    depends_on:
      - spark-cassandra-master
    mem_limit: 2g
